apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "distributed-jmeter.fullname" . }}-server
  labels:
    app.kubernetes.io/name: {{ include "distributed-jmeter.name" . }}
    helm.sh/chart: {{ include "distributed-jmeter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "distributed-jmeter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "distributed-jmeter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: server
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - '-c'
          args:
            - echo server.rmi.ssl.disable=true >> $JMETER_HOME/bin/user.properties && /docker-entrypoint.sh server
          env:
            - name: JVM_ARGS
              value: {{ .Values.jvmArgs }}
          ports:
            - containerPort: 50000
            - containerPort: 1099
